language: python
python:
  - "3.4_with_system_site_packages"
sudo: required
dist: trusty
notifications:
  email: false
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install -y zsh sudo gnupg cryptsetup pinentry-curses gawk
install:
  - wget https://files.dyne.org/tomb/tomb-2.2.tar.gz
  - tar xvfz tomb-2.2.tar.gz
  - pushd tomb-2.2 && sudo make install && popd
  - python setup.py install
  - pip3 install PyQt5
  - pip3 install coverage
  - pip3 install coveralls
  - pip3 install pytest
  - pip3 install pytest-cov
  - pip3 install pytest-mock
  - pip3 install pytest-qt
  - pip3 install pytest-xvfb
script:
  - py.test -v --cov=./
after_success:
  - coveralls