language: python
python: 3.5
sudo: required
dist: trusty
notifications:
  email: false
sudo: required
before_install:
  - wget https://files.dyne.org/tomb/tomb-2.2.tar.gz
  - tar xvfz tomb-2.2.tar.gz
  - pushd tomb-2.2 && make install && popd
install:
  - python setup.py install
  - pip3 install PyQt5
  - pip3 install coverage
  - pip3 install coveralls
  - pip3 install pytest
  - pip3 install pytest-cov
  - pip3 install pytest-mock
  - pip3 install pytest-qt
  - pip3 install pytest-xvfb
script:
  - py.test -v --cov=./
after_success:
  - coveralls