language: python
python: 3.5
sudo: required
dist: trusty
notifications:
  email: false
sudo: required
install:
  - python setup.py install
  - pip install pyqt5
  - pip install coverage
  - pip install coveralls
  - pip install pytest
  - pip install pytest-cov
  - pip install pytest-mock
  - pip install pytest-qt
  - pip install pytest-xvfb
script:
  - py.test -v --cov=./
after_success:
  - coveralls